#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: docker-operator-build
  namespace: galasa-tekton
spec:
  resources:
  - name: git-docker
    type: git
  params:
  - name: distBranch
    type: string
  - name: noPush
    type: string
    default: ""
  tasks:
  - name: docker-operator-build
    taskRef:
      name: docker-operator-build
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: extensionsSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/extensions/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    - name: noPush
      value: $(params.noPush)
    resources:
      inputs:
      - name: git-docker
        resource: git-docker
